name: codeserver Docker Image
on:
  push:
    paths:
      - 'codeserver/**'
      - '.github/workflows/codeserver.yaml'
  schedule:
      - cron: '0 0 * * 0'

jobs: 
  release:
    name: Build and Release Deploy Image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Log in to the Github Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all    
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push images
      uses: docker/build-push-action@v5
      with:
        context: codeserver
        push: true
        tags: ghcr.io/iaacautomation/codeserver:latest
        platforms: linux/amd64
        build-args: CHANNEL=nightly
