name: Deploy Image with AWS
on:
  push:
    paths:
      - 'deploy/**'
      - '.github/workflows/deploy.yaml'

jobs: 
  release:
    name: Build and Release Deploy Image
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    permissions:
      id-token: write
      contents: write
      pull-requests: write
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all    
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    
    - name: Log in to the Github Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Log in to the Docker Container registry
      if: contains(github.ref,'tag')
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_ACCOUNT }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get latest Runner Version
      id: versions
      run: |
        echo runner=`curl --silent "https://api.github.com/repos/actions/runner/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'|cut -b 2-` >> $GITHUB_OUTPUT
        echo container_hooks=`curl --silent "https://api.github.com/repos/actions/runner-container-hooks/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'|cut -b 2-` >> $GITHUB_OUTPUT
        echo helmfile=`curl --silent "https://api.github.com/repos/helmfile/helmfile/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'|cut -b 2-` >> $GITHUB_OUTPUT
        echo kubectl=`curl -L -s https://dl.k8s.io/release/stable.txt`
        echo helm=`curl --silent "https://api.github.com/repos/helm/helm/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'` >> $GITHUB_OUTPUT

    - name: Test Build for deploy
      if: "${{ github.event_name == 'push' && ! contains(github.ref,'tag') }}"
      uses: docker/build-push-action@v5
      with:
        context: deploy
        push: true
        tags: ghcr.io/iaacautomation/deploy:test
        platforms: linux/amd64,linux/arm64
        build-args: |
          RUNNER_VERSION=${{ steps.versions.outputs.runner }}
          RUNNER_CONTAINER_HOOKS_VERSION=${{ steps.versions.outputs.container_hooks }}
          HELMFILE_VERSION=${{ steps.versions.outputs.helmfile }}
          KUBECTL_VERSION=${{ steps.versions.outputs.kubectl }}
          HELM_VERSION=${{ steps.versions.outputs.helm }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
 
    - name: Get tag
      if: contains(github.ref,'tag')
      id: tag
      uses: devops-actions/action-get-tag@v1.0.1
      with:
        strip_v: true

    - name: Log in to the Gitlab Container registry
      if: contains(github.ref,'tag')
      uses: docker/login-action@v3
      with:
        registry: registry.gitlab.com
        username: ${{ secrets.GITLAB_ACCOUNT }}
        password: ${{ secrets.GITLAB_TOKEN }} 

    - name: Configure AWS credentials
      if: contains(github.ref,'tag')
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-duration-seconds: 900
        role-session-name: GitHub

    - name: Login to Amazon ECR
      if: contains(github.ref,'tag')
      run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO_PATH }}

    - name: Build and Push images
      if: contains(github.ref,'tag')
      uses: docker/build-push-action@v5
      with:
        context: deploy
        push: true
        tags: |
          ghcr.io/iaacautomation/deploy:${{steps.tag.outputs.tag}}
          ghcr.io/iaacautomation/deploy:latest
          ${{ secrets.GITLAB_REGISTRY_PATH }}/deploy:latest
          ${{ secrets.DOCKERHUB_ACCOUNT }}/deploy:${{steps.tag.outputs.tag}}
          ${{ secrets.DOCKERHUB_ACCOUNT }}/deploy:latest
          ${{ secrets.ECR_REPO_PATH }}/deploy:${{steps.tag.outputs.tag}}
          ${{ secrets.ECR_REPO_PATH }}/deploy:latest
        platforms: linux/amd64 ,linux/arm64
        build-args: DISTRO=${{ vars.BASE_IMAGE }}
        cache-from: type=gha
