name: Nginx Docker Image
on:
  push:
    paths:
      - 'nginx/**'
      - '.github/workflows/nginx.yaml'
  schedule:
      - cron: '0 0 * * 0'

jobs: 
  release:
    name: Build and Release Deploy Image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Log in to the Gitlab Container registry
      if: contains(github.ref,'tag')
      uses: docker/login-action@v3
      with:
        registry: registry.gitlab.com
        username: ${{ secrets.GITLAB_ACCOUNT }}
        password: ${{ secrets.GITLAB_TOKEN }} 

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all    
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push images
      uses: docker/build-push-action@v5
      with:
        context: nginx
        push: true
        tags: ${{ secrets.GITLAB_REGISTRY_PATH }}/nehraconsultancy/k8s/nginx:latest
        platforms: linux/amd64


